//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuellaMediweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioHuella
    {
        public long id { get; set; }
        public Nullable<long> usuarioid { get; set; }
        public byte[] huella { get; set; }
        public string estado { get; set; }
    }
}
